### ISSUE TITLE
Duplicated files

### ISSUE THREAD

**Issue by orensbruli** [ljmanso/AGM#35]
These two files in the repo are very similar, not identical. Which one should be kept and which removed? Which should be installed?

https://github.com/ljmanso/AGM/blob/current/python/AGGL.py
https://github.com/ljmanso/AGM/blob/current/parser/AGGL.py

The same happens with 

https://github.com/ljmanso/AGM/blob/current/python/pyparsinglocal.py
https://github.com/ljmanso/AGM/blob/current/parser/pyparsinglocal.py

but in this case, are identical. Are both needed?

Thank you.

**Comment by ljmanso** [comment]
The file pyparsinglocal.py is the same in both directories, but the copy in `parser` doesn't seem to be used (`cat CMakeLists.txt |grep AGGL.py`). As you pointed out, AGGL.py changes, but the copy in `parser` is not used either. I'd say it's safe to remove the copies in the `parser` subdirectory.

I just removed the files from the repository.

Thank you for spotting the duplication @orensbruli !
